<?php

namespace BattleshipBundle\Repository;

/**
 * AircraftCarrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AircraftCarrierRepository extends \Doctrine\ORM\EntityRepository
{
}
