<?php

namespace BattleshipBundle\Repository;

/**
 * BattleshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleshipRepository extends \Doctrine\ORM\EntityRepository
{
}
