<?php

namespace BattleshipBundle\Repository;

/**
 * CruiserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CruiserRepository extends \Doctrine\ORM\EntityRepository
{
}
