<?php

namespace BattleshipBundle\Repository;

/**
 * DestroyerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestroyerRepository extends \Doctrine\ORM\EntityRepository
{
}
