<?php

namespace BattleshipBundle\Repository;

/**
 * ShipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipRepository extends \Doctrine\ORM\EntityRepository
{
}
