<?php

namespace BattleshipBundle\Repository;

/**
 * ShotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShotRepository extends \Doctrine\ORM\EntityRepository
{
}
