<?php

namespace BattleshipBundle\Repository;

/**
 * SubmarineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmarineRepository extends \Doctrine\ORM\EntityRepository
{
}
